spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
  file:
    name: /var/log/entropy/app.log

exchange:
  boboo:
    rest:
      scheme: https
      host: api.boboo.vip
      auth-header-name: X-BH-APIKEY
      open-orders: /openapi/v1/openOrders
      request-orders: /openapi/v1/order
      cancel-orders: /openapi/v1/order
    websocket:
      uri: wss://wsapi.boboo.vip/openapi/quote/ws/v1
      timeout: 60000
    orderbook:
      topic: depth
      event: sub
      params:
        binary: false
    apikey:
      accessKey: DfzOAIhNGl0wMK4tgYsL28ytpuasP6OdOnIZg3jlhqYN4RoKvXgeHMVtwmGASJJO
      secretKey: cEVZsBwJIyM6eyWXoKMZzH4gTYMhR0lucMITGblWa3zgAnjxHxMjA1VSTC596SXq
    receiveTimeWindow: 5000

reactor:
  netty:
    http:
      server:
        AccessLog: INFO

entropy:
  userDetail:
    username: mmadmin
    password: oq6343wy@@
  symbols: GTAX2USDT,MOIUSDT,DGCUSDT
  apiKeys:
    gtax2usdt:
      accessKey: WHgLvRJllxqilnP0CSgHCBnuJoteNwiIkSTSY7Cqq9c9AuU0zqYXVH4ENFRzKZ83
      secretKey: 0le5t8SgaK7mLOBzPvHDgqKt0C2x8H6ThO7Vi3ZgPqqKgXuv9OmGsIvMfcuYJFun
    moiusdt:
      accessKey: 5WaXKrsVSP3WDWITF5tG3ZbA6UBPEbwkNumMpRhlqTEbkQczXzd7TTDizIpLRlwG
      secretKey: C8y7NdpTpTyh6HDctCpTNivCYD9KkEmkS0DMqZYqgNGIAJ3WAAAgL7TC0W3XqpIq
    dgcusdt:
      accessKey: VFFnCtzstJqR46tvzK3JcgFqZJBEyG4y20odnNWPUNONO34cjmMTV56HS2bDJQyF
      secretKey: kbAJJfE3DXsfEAZCGtdG5q5fmYaZUdvDLD0ySuE06OhN9nGupj6tRIaWcGLZhzro