spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
  file:
    name: /var/log/entropy/app.log

exchange:
  boboo:
    rest:
      scheme: https
      host: api.bhex.com
      auth-header-name: X-BH-APIKEY
      open-orders: /openapi/v1/openOrders
      request-orders: /openapi/v1/order
      cancel-orders: /openapi/v1/order
    websocket:
      uri: wss://wsapi.bhex.com/openapi/quote/ws/v1
      timeout: 60000
    orderbook:
      topic: depth
      event: sub
      params:
        binary: false
    receiveTimeWindow: 5000
  bigone:
    rest:
      scheme: https
      host: big.one
      open-orders: /api/v3/viewer/orders
      request-orders: /api/v3/viewer/orders
      cancel-orders: /api/v3/viewer/orders/{id}/cancel
    websocket:
      uri: wss://big.one/ws/contract/v2
      timeout: 60000
    receiveTimeWindow: 5000
reactor:
  netty:
    http:
      server:
        AccessLog: INFO

entropy:
  userDetail:
    username: mmadmin
    password: oq6343wy@@
  symbols:
    boboo:
      - GTAX2USDT
      - MOIUSDT
    bigone:
      - OAUSDT
  apiKeys:
    boboo:
      gtax2usdt:
        accessKey: vLpYoIFCHgnkJV0nFIwNzyUcXnDRBKg0GsVQZsemx0mN3gUINfFDxJlJNxbUAxWp
        secretKey: JeL98KsXWyatA3QmmQF4WsvyBUeiMut6QEgJJDoZEK5hJwLcPdiifU3QDBdye5c0
      moiusdt:
        accessKey: XQBxuCfJ6Fq8k44wQC00qCaxVxqs15ssFtBIOf5wIMWT9DszWHUUYBSyzDxTZ9e9
        secretKey: pGn7s2vzbfJUt8vLuABPwYEfIlrfIs1AL8uzVMAn6Wxz5xzc70In5VBpBkFskScR
    bigone:
      oausdt:
        accessKey: fad1a6eb-f6b0-11eb-87a8-3632f06506f2
        secretKey: 7392C9364FBE3B6869C55061E76FF37375BCFB55825245F7D144EBF0D30F034D