spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  thymeleaf:
    cache: false
exchange:
  boboo:
    rest:
      scheme: https
      host: api.boboo.vip
      auth-header-name: X-BH-APIKEY
      open-orders: /openapi/v1/openOrders
      request-orders: /openapi/v1/order
      cancel-orders: /openapi/v1/order
    websocket:
      uri: wss://wsapi.boboo.vip/openapi/quote/ws/v1
    orderbook:
      topic: depth
      event: sub
      params:
        binary: false
    apikey:
      accessKey: ulty827N2vakJap9OdAAejTe7VwykXxUplXSbPGhkLq5r5ImeXACdcr3pZhl6inF
      secretKey: QCzWtRLiuB1vyd1wrmcpZ7m2HywSzasGhQv0olXvUXxpezNhn9RQwFnW2nWYX6lH
    receiveTimeWindow: 5000
