spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
  file:
    name: /var/log/entropy/app.log

exchange:
  boboo:
    rest:
      scheme: https
      host: api.bhex.com
      auth-header-name: X-BH-APIKEY
      open-orders: /openapi/v1/openOrders
      request-orders: /openapi/v1/order
      cancel-orders: /openapi/v1/order
    websocket:
      uri: wss://wsapi.bhex.com/openapi/quote/ws/v1
      timeout: 60000
    orderbook:
      topic: depth
      event: sub
      params:
        binary: false
    apikey:
      accessKey: DfzOAIhNGl0wMK4tgYsL28ytpuasP6OdOnIZg3jlhqYN4RoKvXgeHMVtwmGASJJO
      secretKey: cEVZsBwJIyM6eyWXoKMZzH4gTYMhR0lucMITGblWa3zgAnjxHxMjA1VSTC596SXq
    receiveTimeWindow: 5000
  bigone:
    websocket:
      uri: wss://big.one/ws/contract/v2
      timeout: 60000

reactor:
  netty:
    http:
      server:
        AccessLog: INFO

entropy:
  userDetail:
    username: mmadmin
    password: oq6343wy@@
  symbols: GTAX2USDT,MOIUSDT
  apiKeys:
    gtax2usdt:
      accessKey: vLpYoIFCHgnkJV0nFIwNzyUcXnDRBKg0GsVQZsemx0mN3gUINfFDxJlJNxbUAxWp
      secretKey: JeL98KsXWyatA3QmmQF4WsvyBUeiMut6QEgJJDoZEK5hJwLcPdiifU3QDBdye5c0
    moiusdt:
      accessKey: XQBxuCfJ6Fq8k44wQC00qCaxVxqs15ssFtBIOf5wIMWT9DszWHUUYBSyzDxTZ9e9
      secretKey: pGn7s2vzbfJUt8vLuABPwYEfIlrfIs1AL8uzVMAn6Wxz5xzc70In5VBpBkFskScR